function cfg = defaultConfig(runFolder)
% postprocess.defaultConfig  Minimal config for refactored post-processing.

if nargin < 1
    runFolder = pwd;
end

cfg = struct();
cfg.runFolder = string(runFolder);
cfg.runIndex = 0;
cfg.recordName = "scope";

cfg.constants = postprocess.defaultConstants();
cfg.phys_constants = postprocess.defaultPhysConstants();

cfg.processing = struct();
cfg.processing.shorten = 1;
cfg.processing.makePlots = false;
cfg.processing.saveProcessedMat = true;
cfg.processing.saveSummaryJson = true;

cfg.physics = struct();

cfg.physics.S1 = struct( ...
    'date', datetime("today"), ...
    'kappa', 0.01, ...
    'kappa_I', 0.35, ...
    'eta_signal_col_CWDM', 0.72, ...
    'P_SPDC', 1.2e-6, ...
    'NE', 806, ...
    'P_b', 423e-6, ...
    'comments', "Channel 1 physics package");

cfg.physics.S2 = struct( ...
    'date', datetime("today"), ...
    'kappa', 0.011, ...
    'kappa_I', 0.34, ...
    'eta_signal_col_CWDM', 0.72, ...
    'P_SPDC', 1.15e-6, ...
    'NE', 790, ...
    'P_b', 423e-6, ...
    'comments', "Channel 2 physics package");

cfg.channels = struct();
cfg.channels.S1 = struct('label', "S1", 'homodyneChannel', 2, 'modChannel', 1);
cfg.channels.S2 = struct('label', "S2", 'homodyneChannel', 3, 'modChannel', 4);
end
