% Example: single automated acquisition from a Teledyne LeCroy scope.
%
% Before running:
%   1) Install NI-VISA.
%   2) Put the scope into USBTMC remote mode.
%   3) Replace the VISA resource below with the one shown on the scope.

addpath(fileparts(fileparts(mfilename('fullpath'))));

cfg = lecroy.defaultConfig();
cfg.connection.resource = "USB0::0x05FF::0x1023::123456::INSTR";
cfg.storage.rootDir = fullfile(pwd, 'captures');
cfg.acquisition.runIndex = 0;

% Example fixed setup commands. Replace with your experiment values.
cfg.acquisition.setupCommands = [ ...
    "COMM_HEADER OFF" ...
    "TRMD STOP" ...
    % trace visibility
    "C1:TRA ON" ...
    "C2:TRA ON" ...
    "C3:TRA ON" ...
    "C4:TRA ON" ...
    % volt div
    "C1:VDIV 1V" ...
    "C2:VDIV 20mV" ...
    "C3:VDIV 20mV" ...
    "C4:VDIV 1V" ...
    % offset
    "C1:OFST 0V" ...
    "C2:OFST 0V" ...
    "C3:OFST 0V" ...
    "C4:OFST 0V" ...
    % BERT sig trigger (C1)
    "C1:TRLV 1.91V" ...
    "TRSE EDGE,SR,C1" ...
    "C1:TRSL EITHER" ...
    "TRMD NORMAL" ...
    % time div + span
    "TDIV 20MS" ...
    "MSIZ 200K"

    ];

result = lecroy.acquireRun(cfg);
disp(result.manifestPath)
