function cfg = defaultConfig()
% lecroy.defaultConfig  Default configuration for LeCroy acquisition package.
%
% This package targets Teledyne LeCroy MAUI oscilloscopes over a VISA
% connection, with USBTMC as the default transport. The implementation is
% intentionally conservative: it uses legacy SCPI/IEEE 488.2 style commands
% plus INSPECT? queries so the acquired traces can be exported directly into
% the two-column CSV format already consumed by the user's post-processing
% code.

cfg = struct();

% ---- Connection ----
cfg.connection = struct();
cfg.connection.resource = "USB0::0x0000::0x0000::INSTR"; % replace with scope VISA address
cfg.connection.transport = "USBTMC";
cfg.connection.timeoutSeconds = 60;
cfg.connection.preferVisadev = true;
cfg.connection.readTerminator = "LF";
cfg.connection.writeTerminator = "LF";
cfg.connection.clearOnConnect = true;

% ---- Acquisition ----
cfg.acquisition = struct();
cfg.acquisition.channels = [1 2 3 4];
cfg.acquisition.channelLabels = struct(...
    'C1', "S1_mod", ...
    'C2', "S1_homodyne", ...
    'C3', "S2_homodyne", ...
    'C4', "S2_mod");
cfg.acquisition.recordName = "scope";
cfg.acquisition.runIndex = 0;
cfg.acquisition.acquireMode = "single"; % currently only single is automated here
cfg.acquisition.waitTimeoutSeconds = 30;
cfg.acquisition.waitAfterIdleSeconds = 1.0;
cfg.acquisition.stopBeforeSetup = true;
cfg.acquisition.clearSweeps = false;
cfg.acquisition.setCommHeaderOff = true;

% Optional instrument commands executed before arming. These can be legacy
% commands like C1:VDIV 200 mV or VBS wrappers like:
%   "VBS 'app.acquisition.triggermode = \"stopped\" '"
cfg.acquisition.setupCommands = strings(0,1);

% Optional commands executed immediately after arming and before readback.
cfg.acquisition.postArmCommands = strings(0,1);

% ---- Transfer ----
cfg.transfer = struct();
cfg.transfer.dataQuery = "INSPECT"; % only INSPECT implemented here
cfg.transfer.dataBlock = "DATA_ARRAY_1";
cfg.transfer.dataType = "FLOAT"; % returns scaled volts/units
cfg.transfer.includeDescriptorSnapshot = true;
cfg.transfer.queryVariables = [ ...
    "HORIZ_INTERVAL" ...
    "HORIZ_OFFSET" ...
    "VERTICAL_GAIN" ...
    "VERTICAL_OFFSET" ...
    "TIMEBASE" ...
    "COMM_TYPE" ...
    "COMM_ORDER" ...
    "WAVE_ARRAY_COUNT" ...
    "PNTS_PER_SCREEN" ...
    "FIRST_VALID_PNT" ...
    "LAST_VALID_PNT" ...
    "VERTUNIT" ...
    "HORUNIT" ...
    ];

% ---- Storage ----
cfg.storage = struct();
cfg.storage.rootDir = fullfile(pwd, 'data');
cfg.storage.createDateFolder = true;
cfg.storage.runFolderPattern = "run_%05d";
cfg.storage.writeCsv = true;
cfg.storage.csvHeaderLines = [ ...
    "LeCroy automated acquisition export" ...
    "Columns: Time,Amplitude" ...
    "Generated by lecroy.acquireRun" ...
    "Time(s),Amplitude(V)" ...
    ];
cfg.storage.writeMat = true;
cfg.storage.writeManifestJson = true;

% ---- Logging ----
cfg.logging = struct();
cfg.logging.verbose = true;

% ---- Brain / sweep control ----
cfg.brain = struct();
cfg.brain.runDurationSeconds = 60*3600; % one hour
cfg.brain.pauseBetweenRunsSeconds = 0;
cfg.brain.processAfterAcquire = true;
cfg.brain.stopOnError = true;
cfg.brain.saveSweepSummary = true;

% ---- Post-processing ----
cfg.postprocess = postprocess.defaultConfig(cfg.storage.rootDir);
cfg.postprocess.runIndex = cfg.acquisition.runIndex;

end
